on: [push]
name: Linux_Container_Workflow
 
env:
 RESOURCE_GROUP: ignitedemo1
 CONTAINER_REGISTRY_NAME: acrevivek12
 
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest 
        steps: 
        # checkout the repo 
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v2
          
                  
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}


        - name: create subscription
          uses: azure/CLI@v1 
          with:
             azcliversion: 2.9.1
             inlineScript: |
                az deployment group create --resource-group ${{ env.RESOURCE_GROUP }} --template-file .cloud/.azure/deploy.json \
                --parameters .cloud/.azure/deploy.params.json patToken=${{secrets.PATTOKEN}} \
                containerRegistryName=${{ env.CONTAINER_REGISTRY_NAME }} repo_name=$GITHUB_REPOSITORY
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io 
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }} 
        - run: |
            docker pull houssemdocker/angular-app:latest
            docker tag houssemdocker/angular-app:latest ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io/sample_image:v1
            docker push ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io/sample_image:v1 
